name: deployment
on:
  push:
    branches:
      - main
jobs:

  deploy:
    name: Deploy Frontend
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Digital Ocean droplet via SSH action
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            # Go to bot repository
            cd ../home/ueprod/frontend/
            # Pull changes
            git pull
            # Install dependencies
            npm i
            # Forever restart
            npm run build